* libmpdel

  #+BEGIN_HTML
      <p>
        <a href="https://stable.melpa.org/#/libmpdel">
          <img alt="MELPA Stable" src="https://stable.melpa.org/packages/libmpdel-badge.svg"/>
        </a>

        <a href="https://melpa.org/#/libmpdel">
          <img alt="MELPA Stable" src="https://melpa.org/packages/libmpdel-badge.svg"/>
        </a>

        <a href="https://gitlab.petton.fr/mpdel/libmpdel/commits/master">
          <img alt="pipeline status" src="https://gitlab.petton.fr/mpdel/libmpdel/badges/master/pipeline.svg" />
        </a>

        <a href="https://liberapay.com/DamienCassou/donate">
          <img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg">
        </a>
      </p>
  #+END_HTML


** Summary

The package libmpdel is an Emacs library client to communicate with
[[https://www.musicpd.org/][Music Player Daemon]] (MPD), a flexible, powerful, server-side
application for playing music. For a user interface, please check the
[[https://gitlab.petton.fr/mpdel/mpdel][mpdel]] project instead (which depends on this one).

** Installing

Get libmpdel from [[https://melpa.org/#/libmpdel][melpa]] or [[https://stable.melpa.org/#/libmpdel][melpa stable]]. You can also clone the git
repository.

You need to install and (quickly) configure an [[https://www.musicpd.org/][MPD server]] if you don't
have any yet. Don't worry, that's simple and you won't regret it.

** Usage

This code is a library and is meant for Emacs Lisp developers. The
source code is well documented and organized in sections. Please have
a look at it.

*** Entities

The library is implemented around a set of entities.

| *Name*           | *Type*    | *Fields*             | *Description*                                    |
|------------------+-----------+----------------------+--------------------------------------------------|
| song             | structure | name, album, file, … |                                                  |
| album            | structure | name, artist         |                                                  |
| artist           | structure | name                 |                                                  |
| stored-playlist  | structure | name                 | A named user-specified sequence of songs         |
| search-criteria  | structure | type, what           | Read the [[https://www.musicpd.org/doc/protocol/database.html][protocol documentation]]                  |
|------------------+-----------+----------------------+--------------------------------------------------|
| current-playlist | symbol    | /none/               | Represent the currently played sequence of songs |
| artists          | symbol    | /none/               | Represent the set of all artists                 |
| stored-playlists | symbol    | /none/               | Represent the set of all stored playlists        |

Many functions in MPDel work on several kinds of entities (e.g.,
~libmpdel-list~). These methods are implemented with ~cl-defgeneric~
and ~cl-defmethod~.

** License

See [[file:COPYING][COPYING]]. Copyright (c) 2018 Damien Cassou.

  #+BEGIN_HTML
  <a href="https://liberapay.com/DamienCassou/donate">
    <img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg">
  </a>
  #+END_HTML

#  LocalWords:  MPDel MPD minibuffer
